version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3080:80"
    depends_on:
      - nodeserver
      - client
  nodeserver:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGO_URL=mongodb+srv://VratikZade:vratikzade@cluster0.nws17vq.mongodb.net/?retryWrites=true&w=majority
      - JWTSECRET=ZomatoApp
      - AWS_S3_ACCESS_KEY=AKIARXOOVFAJTFVSBFOC
      - AWS_S3_SECRET_KEY=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
      - GOOGLE_CLIENT_ID=1093757863142-enhpm5looumsigis8uqbtj1g8te0so03.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    ports:
      - "4000:4000"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"